spring:
  application:
    name: Logistic-Application

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: mysecretpassword

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-message: always
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

driver:
  defaultAverageSpeed: 80
  defaultNumberOfHoursWorkedLimit: 176

truck:
  default-seats: 4

default:
  number-of-hours-worked: 0
  size-of-submitting-orders: 10

jwt:
   secret: U29tZSBzZWN1cmUga2V5IHdpdGggY29tcGxleCBzZWFyY2ggbGVuZ3Ro
   lifetime: 3600000